# Generated by Django 5.2.9 on 2025-12-02 23:23

import django.core.validators
import django.db.models.deletion
import pdfapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('source_file', models.FileField(help_text='Upload DOCX or PPTX file', upload_to=pdfapp.models.upload_to_pdf_source, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pptx'])], verbose_name='source file')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=pdfapp.models.upload_to_pdf_output, verbose_name='PDF file')),
                ('html_file', models.FileField(blank=True, null=True, upload_to=pdfapp.models.upload_to_pdf_output, verbose_name='HTML file')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='page count')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'PDF document',
                'verbose_name_plural': 'PDF documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('message', models.TextField(verbose_name='message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pdfapp.pdfdocument')),
            ],
            options={
                'verbose_name': 'conversion log',
                'verbose_name_plural': 'conversion logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
