# Generated by Django 5.2.9 on 2025-12-02 23:23

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'about section',
                'verbose_name_plural': 'about sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('short_description', models.TextField(max_length=500, verbose_name='short description')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='content')),
                ('image', models.ImageField(upload_to='activities/', verbose_name='featured image')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='event time')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('short_description', models.TextField(max_length=500, verbose_name='short description')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='image')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/files/', verbose_name='attachment')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='priority')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ['-is_featured', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('is_replied', models.BooleanField(default=False, verbose_name='is replied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon class')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='display number')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('subtitle', models.TextField(blank=True, verbose_name='subtitle')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='button text')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='button URL')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='background image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'hero slide',
                'verbose_name_plural': 'hero slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='location name')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='Google Maps embed code')),
                ('working_hours', models.TextField(blank=True, verbose_name='working hours')),
                ('is_main', models.BooleanField(default=False, verbose_name='is main office')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SaiReeCMPO', max_length=200, verbose_name='site name')),
                ('site_title', models.CharField(default='Government Office CMS', max_length=200, verbose_name='site title')),
                ('site_description', models.TextField(blank=True, verbose_name='site description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='favicon')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('line_url', models.URLField(blank=True, verbose_name='LINE URL')),
                ('footer_text', models.TextField(blank=True, verbose_name='footer text')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='copyright text')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('image', models.ImageField(upload_to='team/', verbose_name='photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionMissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission'), ('value', 'Value')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='content')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon class')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vmv/', verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'vision/mission/value',
                'verbose_name_plural': 'vision/mission/values',
                'ordering': ['type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/gallery/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.activity')),
            ],
            options={
                'verbose_name': 'activity gallery image',
                'verbose_name_plural': 'activity gallery images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('url', models.CharField(help_text='Use # for anchor links', max_length=200, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class', max_length=50, verbose_name='icon class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.navbarmenu', verbose_name='parent menu')),
            ],
            options={
                'verbose_name': 'navbar menu',
                'verbose_name_plural': 'navbar menus',
                'ordering': ['order'],
            },
        ),
    ]
